Fixes issue 9578
webdriverio/webdriverio pull request #11464
Opened 2023-10-18 15:26 UTC by KierenLWoods

## Proposed changes

This change fixes #9578 . There was an issue where if a user answered the test file generation location questions with a response such as 'y', the wizard would then put all the files in the current directory. With this fix even if 'y' was to be passed the files would then be generated in a folder named y under the project root. This PR also fixes a bug around the step definition file location. 

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### Reviewers: @webdriverio/project-committers

2023-10-18 15:32 UTC, christian-bromann commented on packages/wdio-cli/src/utils.ts
> +    const destStepRootPath = path.resolve(projectRootDir, (path.dirname(answers.stepDefinitions || '') === '.' ? path.resolve(answers.stepDefinitions || '') : path.dirname(answers.stepDefinitions ||
same

2023-10-20 10:36 UTC, erwinheitzman requested changes

2023-10-20 10:36 UTC, erwinheitzman commented on packages/wdio-cli/src/utils.ts
> +            (path.dirname(pageObjectAnswer) === '.' ? path.resolve(pageObjectAnswer) : path.dirname(pageObjectAnswer)).replace(/\*\*$/, ''))
Let's make a function that automatically resolves this by taking the answer, check if . and resolve if needed

2023-11-06 23:06 UTC, christian-bromann approved these changes
Awesome, great work! LGTM 👍

2023-11-06 23:06 UTC, merged