(@wdio/crossbrowsertesting-service): remove integration to CrossBrowserTesting platform
webdriverio/webdriverio pull request #12433
Opened 2024-03-05 19:50 UTC by christian-bromann

## Proposed changes

The company doesn't seem to exist anymore and all Node.js packages were archived.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Polish (an improvement for an existing feature)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (improvements to the project's docs)
- [ ] Specification changes (updates to WebDriver command specifications)
- [ ] Internal updates (everything related to internal scripts, governance documentation and CI files)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added the necessary documentation (if appropriate)
- [x] I have added proper type definitions for new commands (if appropriate)

## Backport Request

We might want to deprecate the service in v8 but I doubt anyone is using it at this point.

- [ ] This change is solely for `v9` and doesn't need to be back-ported
- [ ] Back-ported PR at `#XXXXX`

## Further comments

n/a

### Reviewers: @webdriverio/project-committers

2024-03-05 20:47 UTC, seanpoulter requested changes
Looks great but we missed removing one section. I wonder if there's a way to configure Docusaurus to fall back to the default so we don't have to maintain as many copies.

2024-03-05 20:47 UTC, seanpoulter commented on website/i18n/es/docusaurus-plugin-content-docs/current/CloudServices.md
> +Si está utilizando el testrunner WDIO, descargue y configure el [`@wdio/testingbot-service`](https://github.com/webdriverio/webdriverio/tree/main/packages/wdio-testingbot-service) en su `wdio.conf.js
Ah, we should remove this one.

2024-03-05 22:04 UTC, christian-bromann commented
@seanpoulter good catch, found more occurrences and removed them.

2024-03-06 01:00 UTC, seanpoulter approved these changes

2024-03-06 03:42 UTC, merged