fix(@wdio/runner): Respect excludes in capabilities in multiremote case.
webdriverio/webdriverio pull request #13878
Opened 2024-11-12 20:41 UTC by damencho

Fixes #13875.

When a spec is excluded from some capability there is no point of starting the browser session for it.

## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

When spec is excluded in multiremote the browser sessions are still created for it.

```
specs: [
        'test/example.spec.ts'
    ],

    capabilities: {
        participant1: {
            capabilities: {
                browserName: 'chrome'
            }
        },
        participant2: {
            capabilities: {
                browserName: 'chrome',
                'wdio:exclude': [
                    'test/example.spec.ts'
                ]
            }
        }
    },
```
This will create two browser sessions for the test and the PR will change that to be only one. 

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Polish (an improvement for an existing feature)
- [ X ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (improvements to the project's docs)
- [ ] Specification changes (updates to WebDriver command specifications)
- [ ] Internal updates (everything related to internal scripts, governance documentation and CI files)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [ X ] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ X ] I have added the necessary documentation (if appropriate)
- [ X ] I have added proper type definitions for new commands (if appropriate)

## Backport Request

[//]: # (The current `main` branch is the development branch for WebdriverIO v9. If your change should be released to the current major version of WebdriverIO (v8), please raise another PR with the same changes against the `v8` branch.)

- [ X ] This change is solely for `v9` and doesn't need to be back-ported
- [ ] Back-ported PR at `#XXXXX`

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

It was discussed in https://github.com/webdriverio/webdriverio/issues/13875

### Reviewers: @webdriverio/project-committers

2024-11-13 16:15 UTC, christian-bromann requested changes
Can we add some unit tests for this as well?

2024-11-13 16:15 UTC, christian-bromann commented on packages/wdio-runner/src/index.ts
> +        this._caps = filteredCaps
```suggestion
        this._caps = this._isMultiremote
            ? Object.entries(caps).reduce((filteredCaps, [browserName, browserCaps]) => {
                const ex = browserCaps.capabilities['wdio:exclude']
                if (ex) {
                    const sp = this._configParser?.getSpecs(specs, ex)
                    if (sp && sp.length === 0) {
                        return
                    }
                }
                filteredCaps[browserName] = browserCaps
            }, {} Capabilities.RequestedMultiremoteCapabilities)
            : caps
```

2024-11-13 16:15 UTC, christian-bromann commented on packages/wdio-runner/src/index.ts
> +        }, filteredCaps)
```suggestion
        }, this._caps)
```

2024-11-13 16:15 UTC, christian-bromann commented on packages/wdio-runner/src/index.ts
> +            filteredCaps as WebdriverIO.Capabilities,
```suggestion
            this._caps as WebdriverIO.Capabilities,
```

2024-11-13 16:15 UTC, christian-bromann commented on packages/wdio-runner/src/index.ts
> +        const beforeSessionParams: BeforeSessionArgs = [this._config, filteredCaps, this._specs, this._cid]
```suggestion
        const beforeSessionParams: BeforeSessionArgs = [this._config, this._caps, this._specs, this._cid]
```

2024-11-13 16:15 UTC, christian-bromann commented on packages/wdio-runner/src/index.ts
> +        this._reporter = new BaseReporter(this._config, this._cid, { ...filteredCaps })
```suggestion
        this._reporter = new BaseReporter(this._config, this._cid, { ...this._caps })
```

2024-11-13 16:15 UTC, christian-bromann commented on packages/wdio-runner/src/index.ts
> +        process.send!({ name: 'testFrameworkInit', content: { cid, filteredCaps, specs, hasTests: this._framework.hasTests() } })
```suggestion
        this._framework = await this.#initFramework(cid, this._config, this._caps, this._reporter, specs)
        process.send!({ name: 'testFrameworkInit', content: { cid, caps: this._caps, specs, hasTests: this._framework.hasTests() } })
```

2024-11-13 16:15 UTC, christian-bromann commented on packages/wdio-runner/src/index.ts
> +        browser = await this._initSession(this._config, filteredCaps)
```suggestion
        browser = await this._initSession(this._config, this._caps)
```

2024-11-13 16:15 UTC, christian-bromann commented on packages/wdio-runner/src/index.ts
> +            const afterArgs: AfterArgs = [1, filteredCaps, this._specs]
```suggestion
            const afterArgs: AfterArgs = [1, this._caps, this._specs]
```

2024-11-13 16:15 UTC, christian-bromann commented on packages/wdio-runner/src/index.ts
> +        const beforeArgs: BeforeArgs = [filteredCaps, this._specs, browser]
```suggestion
        const beforeArgs: BeforeArgs = [this._caps, this._specs, browser]
```

2024-11-13 17:50 UTC, damencho commented
> Can we add some unit tests for this as well?

Is it ok to add them in smoke tests?

2024-11-13 20:01 UTC, christian-bromann commented
> Is it ok to add them in smoke tests?

Yes, you should be able to verify that on x of x session were created.

2024-11-13 21:14 UTC, damencho commented
> > Is it ok to add them in smoke tests?
> 
> Yes, you should be able to verify that on x of x session were created.

Yep, I have added the tests.

2024-11-13 22:59 UTC, christian-bromann commented
Mind signing the CLA?

2024-11-14 00:32 UTC, damencho commented
> Mind signing the CLA?

Yes, I'm working on that with our legal team, sorry for the delay.

2024-11-14 17:00 UTC, damencho commented on packages/wdio-runner/src/index.ts
> +            ? Object.entries(caps).reduce((filteredCaps, [browserName, browserCaps]) => {
I have added it. Thanks.

2024-11-14 18:10 UTC, merged