Update constants.js in wdio-cli with wdio-rerun-service
webdriverio/webdriverio pull request #5740
Opened 2020-08-18 19:49 UTC by mikesalvia

## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [X] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)
- [X] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### Reviewers: @webdriverio/project-committers

2020-08-19 13:31 UTC, mikesalvia commented
@christian-bromann Is this the only place I should update the available service?

2020-08-23 16:46 UTC, christian-bromann requested changes
@mikesalvia please also add it to `/scripts/docs-generation/3rd-party/services.json`, thanks!

2020-08-24 14:39 UTC, mikesalvia commented
@christian-bromann All done!

2020-08-24 16:09 UTC, christian-bromann reviewed
just a minor formatting issue

2020-08-24 16:09 UTC, christian-bromann commented on scripts/docs-generation/3rd-party/services.json
> +    "npmUrl": "https://www.npmjs.com/package/wdio-rerun-service"
```suggestion
  },
  {
    "packageName": "wdio-rerun-service",
    "title": "Re-run Service",
    "githubUrl": "https://github.com/jwplayer/wdio-rerun-service",
    "npmUrl": "https://www.npmjs.com/package/wdio-rerun-service"
```

2020-08-24 16:36 UTC, mikesalvia commented
Accepted and merged in.

2020-08-24 18:28 UTC, christian-bromann approved these changes
Thanks 👍

2020-08-24 18:28 UTC, merged