Document setting download paths with browser.cdp()
webdriverio/webdriverio pull request #5753
Opened 2020-08-24 20:56 UTC by vipulgupta2048

## Proposed changes

Solves #5727 
Added information, links, and code snippet on setting download paths in Devtools Service with browser.cdp() command.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ x ] Documentation update

## Checklist

- [ x ] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ x ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments
If this was tested or we can suggest other solutions, that be great too. 

### Reviewers: @webdriverio/project-committers

2020-08-24 21:17 UTC, christian-bromann requested changes
Minor formatting request.

2020-08-24 21:17 UTC, christian-bromann commented on packages/wdio-devtools-service/README.md
> +            downloadPath: '/home/root/webdriverio-project/',
```suggestion
    behavior: 'allow',
    downloadPath: '/home/root/webdriverio-project/',
```

2020-08-25 06:16 UTC, vipulgupta2048 commented
@christian-bromann  Good to go :rocket:

2020-08-25 07:25 UTC, christian-bromann approved these changes
👍

2020-08-25 07:26 UTC, merged