Fix #5647 : add other check for app capability in browserstack-service
webdriverio/webdriverio pull request #5771
Opened 2020-08-29 02:40 UTC by Virtim

## Proposed changes
This PR is a proposal to fix #5647. The issue is that `global.browser.capabilities.` doesn't contain an `app`. I've added `this.caps.app` which in fact does exist. I kept `global.browser.capabilities.app` in place for backward compatibility. 

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### Reviewers: @webdriverio/project-committers

2020-08-29 09:26 UTC, christian-bromann requested changes
Can we add a test for this?

2020-08-31 22:12 UTC, Virtim commented
Hey Christian, I think there is already test in https://github.com/webdriverio/webdriverio/blob/45e12022d4916cd019d699db3850929d1bbb89a3/packages/wdio-browserstack-service/tests/service.test.js#L176

2020-09-01 07:04 UTC, christian-bromann commented
> I think there is already test in

We need a test where `global.browser.capabilities` doesn't contain an `app` property but `this.caps` within the service is set.

2020-09-02 01:15 UTC, Virtim commented
Oh boy, that what happens when you don't work with unit tests, shame on me. :) I'm sorry! Test added

2020-09-02 07:23 UTC, christian-bromann approved these changes
👍

2020-09-02 07:23 UTC, merged