Update PageObjects.md
webdriverio/webdriverio pull request #5902
Opened 2020-09-29 14:03 UTC by PetrKnedlik

changed page to page.js so it's more clear to everyone

## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [ ] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### Reviewers: @webdriverio/project-committers

2020-09-29 14:05 UTC, PetrKnedlik commented
Small change in documentation

2020-09-29 14:08 UTC, christian-bromann requested changes
One comment otherwise LGTM

2020-09-29 14:08 UTC, christian-bromann commented on docs/PageObjects.md
> +
this empty line seems unnecessary

```suggestion
```

2020-09-30 08:26 UTC, PetrKnedlik commented
@christian-bromann removed

2020-09-30 08:32 UTC, christian-bromann approved these changes
👍

2020-09-30 08:33 UTC, merged