Added possibility to disable automatic strings to unicode translation
webdriverio/webdriverio pull request #5928
Opened 2020-10-05 11:48 UTC by IgorSasovets

## Proposed changes
This is a fix for wdio automatic translation to [unicode issue](https://github.com/webdriverio/webdriverio/issues/4936). In general, user can't send keys that are predefined in the UNICODE_CHARACTERS [list](https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/src/constants.js).

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [X] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [X] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### Reviewers: @webdriverio/project-committers

2020-10-05 12:33 UTC, christian-bromann requested changes
`AddValueOptions` needs to be added [here](https://github.com/webdriverio/webdriverio/blob/master/scripts/type-generation/constants.js)

2020-10-05 12:44 UTC, mgrybyk submitted a review, later dismissed
Please run types tests locally and commit generated d.ts files

2020-10-05 12:44 UTC, mgrybyk commented on scripts/templates/webdriverio.tpl.d.ts
> +        translateToUnicode: boolean
Should be optional

2020-10-05 17:07 UTC, IgorSasovets commented on scripts/templates/webdriverio.tpl.d.ts
> +        translateToUnicode: boolean
Fixed

2020-10-05 17:08 UTC, IgorSasovets commented
@christian-bromann , @mgrybyk , added requested changes to the PR

2020-10-05 19:58 UTC, christian-bromann reviewed
One last thing I've just realised: we are using `AddValueOptions` for `setValue` which seems a bit mis-worded. Can we have a generalised name for it that fits to set and addValue?

2020-10-06 07:06 UTC, IgorSasovets commented
@christian-bromann , I think yes but we should take into an account that `setValue` command uses `addValue` under the hood. So, does it really make sense to rename it? Lastly, it is hard to pick up some general name for this parameter. I would name it `changeValueOptions` because in both cases we change the value of a selected element. Please share your thoughts and suggestions

2020-10-06 07:35 UTC, christian-bromann approved these changes
> I think yes but we should take into an account that setValue command uses addValue under the hood. So, does it really make sense to rename it?

Very good point, let's keep as is. Thank you!

LGTM 👍

2020-10-06 07:42 UTC, merged

2020-10-06 08:24 UTC, IgorSasovets commented
@christian-bromann , thanks a lot!