Fix 5577
webdriverio/webdriverio pull request #5970
Opened 2020-10-11 19:15 UTC by jonesh66

## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### Reviewers: @webdriverio/project-committers

2020-10-11 21:11 UTC, christian-bromann requested changes
@jonesh66 thanks for providing this fix. We need to ensure we have tests for this otherwise changes might cause regressions. Can you add tests for the code changes in this PR?

2020-10-25 18:22 UTC, christian-bromann commented on packages/wdio-reporter/src/index.js
> +        if(content) this.contentPresent = true
```suggestion
        if(content) {
            this.contentPresent = true
        }

```

2020-10-25 18:23 UTC, christian-bromann commented
I think we have a rebase issue here? Do you need help resolve it?

2020-10-26 12:58 UTC, jonesh66 commented
@christian-bromann yes, I was trying to rebase my changes on top of master before pushing them. Github UI says there are conflicts but I can't find them locally. I pulled latest master on my fork. Any suggestions?

2020-10-27 15:59 UTC, christian-bromann commented
@jonesh66 your master branch is outdated, files in `@wdio/reporter` have been ported to TypeScript. I think the best idea is to start from a fresh branch and port of the changes to that. Let me know if you need help with that.

2020-11-02 08:41 UTC, christian-bromann commented
Let's close this in favor of #6060

2020-11-02 08:41 UTC, closed without merging