Fixes #6057
webdriverio/webdriverio pull request #6066
Opened 2020-11-02 19:34 UTC by vmelikyan

## Proposed changes

### Fixes #6057 

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] I have added proper type definitions for new commands (if appropriate)

### Reviewers: @webdriverio/project-committers

2020-11-02 20:07 UTC, christian-bromann requested changes
Can we add unit tests for this?

2020-11-03 07:31 UTC, christian-bromann commented on packages/webdriverio/src/commands/browser/mock.ts
> +            )
Should we make sure that we don't register this twice for a page?

2020-11-03 07:42 UTC, mgrybyk commented on packages/webdriverio/src/commands/browser/mock.ts
> +    if (!SESSION_MOCKS.has(windowHandle) && !this.isSauce) {
I'd better always define a Set per window and check is it empty like https://github.com/webdriverio/webdriverio/compare/mock-multi-window#diff-03e7544b40f7605d80b9c64844538cd8a50ccfdddf92b3c452f30b5fe43bb78eR114

I think this is what @christian-bromann is asking for

2020-11-03 07:47 UTC, mgrybyk requested changes

2020-11-03 07:47 UTC, mgrybyk commented on packages/webdriverio/src/commands/browser/mock.ts
> +        await pages.forEach(async (page: any) => {
I'd define mocks per page rather than have a mock for all pages.
It's impossible to identify where does request come from

2020-11-05 21:30 UTC, vmelikyan commented
Thanks for the feedback. I'll try to fix it over the weekend.

2020-11-16 11:00 UTC, christian-bromann commented
@vmelikyan is there anything I can do to help land this?

2020-11-16 18:18 UTC, vmelikyan commented
@christian-bromann I've copied over @mgrybyk's solution and updated the test.

2020-11-16 18:37 UTC, vmelikyan commented
_Side note:_ Is it really needed to run the unit tests along with `test:eslint test:typings test:coverage` on all platforms? E.g. `linux 10.x, 12.x, 14.x`, `windows` and `macos`

2020-11-16 21:56 UTC, christian-bromann approved these changes
This looks good to me 👍 

@mgrybyk thoughts?

2020-11-16 21:58 UTC, christian-bromann commented
> _Side note:_ Is it really needed to run the unit tests along with `test:eslint test:typings test:coverage` on multiple platforms? E.g. `linux 10.x, 12.x, 14.x`, `windows` and `macos`

Yes. We test on different Node.js versions to ensure that e.g. dependencies are still supported for the range of Node.js versions WebdriverIO is suppose to support. And then we test on different OS platforms to ensure that if someone with a Windows machine wants to contribute to WebdriverIO doesn't see any failing tests which often occur if you assert paths (`/` vs `\\`).

2020-11-17 00:27 UTC, mgrybyk approved these changes

2020-11-17 08:58 UTC, merged