Another take on bug #4953
webdriverio/webdriverio pull request #6076
Opened 2020-11-06 16:31 UTC by oversizedhat

## Proposed changes

Bug fix to https://github.com/webdriverio/webdriverio/issues/4953, as discussed in https://github.com/webdriverio/webdriverio/pull/5040

Hard to say if this solves all issues. I have not added any kind of extensive testing of it but it at least looks like solves our case where we us mocha framework in combo with wdio. Have not tested any other scenario.

The "currentTest" addition to the hook seems to have been expected as its is used (but ignored) in https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-mocha-framework/src/index.js

## Types of changes

- [x ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist
- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### Reviewers: @webdriverio/project-committers

2020-11-10 08:37 UTC, christian-bromann requested changes
I think if this solves the issue for at least Mocha test it is already a step forward. One comment on the implementation.

@BorisOsipov any thoughts?

2020-11-10 08:37 UTC, christian-bromann commented on packages/wdio-allure-reporter/src/index.js
> +            if (this.allure.getCurrentTest().name == testTitle) {
```suggestion
        if (this.isAnyTestRunning() && this.allure.getCurrentTest().name == testTitle) {
```

2020-11-10 08:57 UTC, BorisOsipov commented
@christian-bromann I dont mind.

2020-11-10 13:26 UTC, christian-bromann commented
@oversizedhat please address the comment above and add a unit test for your changes in the Allure reporter. Let me know if you need and help.

2020-11-11 17:21 UTC, oversizedhat commented
cheers @christian-bromann I will take a look into adding some tests

2020-11-16 10:59 UTC, christian-bromann commented
@oversizedhat the change looks good to me, can you squash all commits into one so that the CLA bot is happy? Cheers!

2020-11-16 14:00 UTC, oversizedhat commented
cheers @christian-bromann, will try to wrap it up. Still want to add some kind of test to validate the change too, it was a valid comment.

2020-11-16 16:15 UTC, oversizedhat commented
@christian-bromann cleaned it up now and added at least some basic test to validate that there are no test duplicates in the allure report due to hook start. There is room for more testing but its something at least

2020-11-16 17:12 UTC, christian-bromann approved these changes
Awesome, LGTM 👍

2020-11-16 17:13 UTC, merged