Try to fix @wdio/testingbot-service not using the Tunnel
webdriverio/webdriverio pull request #6105
Opened 2020-11-13 16:15 UTC by testingbot

## Proposed changes

The latest versions of @wdio/testingbot-service is no longer forwarding requests through http://localhost:4445
As a result, webdriverio tests will no longer use the TestingBot Tunnel.

This change includes a tunnelIdentifier instead, which should be passed through as a capability.
I tried to use `tb:options` for this, but for some reason this gets stripped out further down by webdriverio.

This PR does not fix the problem yet. If someone could guide me in how to pass this through the capabilities, then I can adjust this PR.

Many thanks

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

### Reviewers: @webdriverio/project-committers

2020-11-14 00:14 UTC, hieuxlu commented
> This PR does not fix the problem yet. If someone could guide me in how to pass this through the capabilities, then I can adjust this PR.

If you're talking about unit tests, just create a new capabilities object when initializing service launcher.

2020-11-14 08:17 UTC, hieuxlu commented
I highly suspect this was caused by using wrong kind of ES6 export in below line https://github.com/webdriverio/webdriverio/blob/cb633ce0dad3bf1eae4c6ba89928549580d54916/packages/wdio-testingbot-service/src/%40types/testingbot-tunnel-launcher.d.ts#L3 

Caused by #6032 
I should have been `export =` instead of `export default`, like the `testingbot-tunnel-launcher` library did.

```
module.exports = downloadAndRun
module.exports.kill = killTunnel
```

2020-11-14 08:35 UTC, hieuxlu commented
So `testingbot-tunnel-launcher` was using CommonJS export, when using Typescript, we should've used 
```diff
-import testingbotTunnel from 'testingbot-tunnel-launcher'
+import testingbotTunnel = require('testingbot-tunnel-launcher')
```

And in `packages/wdio-testingbot-service/src/@types/testingbot-tunnel-launcher.d.ts`
```diff
@@ -1,6 +1,6 @@
 declare module 'testingbot-tunnel-launcher' {
     const testingbotTunnel: (options: TunnelLauncherOptions, cb: (err: Error, tunnel: TestingbotTunnel) => void) => void;
-    export default testingbotTunnel;
+    export = testingbotTunnel;
 }
```
Could you make this change and, along with correcting logger from `saucelabs` to `testingbot`, I'm really sorry for the breaking change made.

2020-11-14 11:18 UTC, hieuxlu commented
This bug is critical for wdio-testingbot-service so if there's no feedback, I'll submit another PR to fix this today.

2020-11-14 16:07 UTC, hieuxlu requested changes

2020-11-14 16:07 UTC, hieuxlu commented on packages/wdio-testingbot-service/src/launcher.ts
> +        capabilities['tb:options'].tunnelIdentifier = tbTunnelIdentifier
This probably will not work if 2 tests are running in parallel, so I'll revert this and create my null PR

2020-11-14 17:13 UTC, hieuxlu commented
Close in favor of #6109

2020-11-17 01:14 UTC, hieuxlu commented
@testingbot Could you share you config, or a minimal repro? I found your docs on Webdriverio integration to be incorrect
https://testingbot.com/support/getting-started/webdriverjs.html#tunnel
```
exports.config = {
	services: ['testingbot'],
	user: '...',
	key: '...',
	tbTunnel: true
};
```

It should be 
```
exports.config = {
	services: [
           ['testingbot', { tbTunnel: true }]
        ],
	user: '...',
	key: '...',
};
```

2020-11-17 01:17 UTC, hieuxlu commented
This was changed 10 months ago on #4606 in wdio v6. If you have the old config, you should use wdio v5

2020-11-17 09:01 UTC, christian-bromann commented
This wdio config is invalid:
```js
exports.config = {
	services: ['testingbot'],
	user: '...',
	key: '...',
	tbTunnel: true
};
```
options to services have to be passed in through the service list:
```js
exports.config = {
	services: [
           ['testingbot', { tbTunnel: true }]
        ],
	user: '...',
	key: '...',
};
```

2020-11-17 11:42 UTC, hieuxlu commented
@testingbot I could run the minimal repro successfully, what was the issue?
```
D:\repos\webdriverio-reproduce-bug (master -> origin) (wdio-repo-testingbot@1.0.0)
λ yarn wdio
yarn run v1.22.10
$ D:\repos\webdriverio-reproduce-bug\node_modules\.bin\wdio

Execution of 1 spec files started at 2020-11-17T11:39:35.494Z

2020-11-17T11:39:35.500Z DEBUG @wdio/utils:initialiseServices: initialise service "testingbot" as NPM package
2020-11-17T11:39:35.530Z INFO @wdio/cli:launcher: Run onPrepare hook
Tunnel Readyfile already exists, removing
Tunnel is ready
2020-11-17T11:39:51.585Z INFO @wdio/sauce-service: TestingBot tunnel successfully started after 16049.5739ms
```

2020-11-17 13:39 UTC, christian-bromann commented
It seems that the problem is that we modify the [`config` property](https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-testingbot-service/src/launcher.ts#L27-L30) instead of `this.capabilities` as e.g. done in the [selenium-standalone service](https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-selenium-standalone-service/src/launcher.ts#L45-L53).

2020-11-17 15:10 UTC, hieuxlu commented
@christian-bromann But this code has been exactly the same from the first commit, when did things go wrong, and are there any similar services impacted? Is overriding capabilities the only way for this to work?

@testingbot I am able to workaround and connect to the tunnel by specifically setting `hostname`, `port` and `protocol` like below. But on my end, I am unable to connect to `google.com`, could you try setting like below on your end?
```javascript
// wdio.conf.js
	hostname: 'localhost',
	port: 4445,
	protocol: 'http',
```

2020-11-17 15:41 UTC, christian-bromann commented
> when did things go wrong

Unsure. We recently improved services to modify the configuration and connect to things like tunnels or drivers that have been started. Could be the lack of maintenance on the testingbot service

2020-11-17 16:40 UTC, hieuxlu commented
> > when did things go wrong
> 
> Unsure. We recently improved services to modify the configuration and connect to things like tunnels or drivers that have been started. Could be the lack of maintenance on the testingbot service

I could confirm it started with v6, when we drop support for root level config for service. v5 was working fine, but only with root level config. Do you think overriding capabilities like in Selenium standalone service is the only way now?

2020-11-17 16:49 UTC, christian-bromann commented
> Do you think overriding capabilities like in Selenium standalone service is the only way now?

Yes.

2020-11-18 09:24 UTC, christian-bromann commented
@testingbot thanks! There seems to be an error in the unit test:

```
Summary of all failing tests
FAIL packages/wdio-testingbot-service/tests/launcher.test.ts (1102 MB heap size)
  ● wdio-testingbot-service › onPrepare

    TypeError: Cannot read property 'tb:options' of undefined

      28 |         }, this.options.tbTunnelOpts)
      29 | 
    > 30 |         let tbOptions = capabilities['tb:options']
         |                                     ^
      31 |         if (!tbOptions) {
      32 |             tbOptions = {}
      33 |         }

      at TestingBotLauncher.onPrepare (packages/wdio-testingbot-service/src/launcher.ts:30:37)
      at Object.<anonymous> (packages/wdio-testingbot-service/tests/launcher.test.ts:53:26)
```

2020-11-18 13:06 UTC, christian-bromann commented
Thank you @testingbot , we need the author of all commits to sign the CLA before we can merge this.

2020-11-18 14:07 UTC, christian-bromann commented
> Hi @christian-bromann - I've signed the CLA

That doesn't help.

2020-11-18 14:09 UTC, christian-bromann approved these changes
👍

2020-11-18 14:31 UTC, merged