fix for #6151 @wdio/testingbot-service doesn't configure the hostname…
webdriverio/webdriverio pull request #6157
Opened 2020-11-24 14:52 UTC by testingbot

## Proposed changes

This fixes #6151 - our latest change (e92dd59eb08eb0b585ebef2ebad72c26e4946004) was overwriting `tb:options` - this is now fixed with this PR.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### Reviewers: @webdriverio/project-committers

2020-11-24 15:06 UTC, christian-bromann requested changes

2020-11-24 15:06 UTC, christian-bromann commented on packages/wdio-testingbot-service/src/@types/testingbot-service.d.ts
> +    tbTunnelOpts?: any;
Could we get some actual type definition here?

2020-11-24 15:06 UTC, christian-bromann commented on packages/wdio-testingbot-service/src/launcher.ts
> +            Object.keys(capabilities).forEach(browserName => {
let's do a for..of loop instead
```suggestion
            for (const browserName of Object.keys(capabilities)) {
```

2020-11-24 15:06 UTC, christian-bromann commented on packages/wdio-testingbot-service/testingbot-service.d.ts
> +    tbTunnelOpts?: any;
same as first comment

2020-11-24 15:21 UTC, christian-bromann commented on packages/wdio-testingbot-service/src/launcher.ts
> +        const tbTunnelIdentifier = this.options.tbTunnelOpts && this.options.tbTunnelOpts.tunnelIdentifier ? this.options.tbTunnelOpts.tunnelIdentifier : `TB-tunnel-${Math.random().toString().slice(2
```suggestion
        const tbTunnelIdentifier = this.options.tbTunnelOpts?.tunnelIdentifier || `TB-tunnel-${Math.random().toString().slice(2)}`
```

2020-11-24 15:21 UTC, christian-bromann commented on packages/wdio-testingbot-service/src/launcher.ts
> +                const capability = (capabilities as any)[browserName]
```suggestion
                const capability = (capabilities as WebdriverIO.MultiRemoteOptions)[browserName]
```

2020-11-25 10:03 UTC, christian-bromann approved these changes
Awesome, thank you 👍

2020-11-25 10:03 UTC, merged

2020-11-25 12:56 UTC, karfau reviewed
Even though I have no idea why it fixes the issue I reported, I'm glad it does and thank you for the fast fix.

2020-11-25 12:56 UTC, karfau commented on packages/wdio-testingbot-service/testingbot-service.d.ts
> +    apiSecret: string;
Question: Are these options now mandatory? Is there no way to grab the ones from `user`/`key`? (Also it seems to work when not passing any options.)

2020-11-25 12:56 UTC, karfau commented on packages/wdio-testingbot-service/src/@types/testingbot-service.d.ts
> +    tbTunnelOpts?: TunnelLauncherOptions;
Awesome! Thx for adding those types.