Pdf print page
webdriverio/webdriverio pull request #6162
Opened 2020-11-26 03:27 UTC by Maxgit3

## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

#6120 Draft of proposed addition to resolve issue

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

set as a draft to see if this fits the proposed addition.

### Reviewers: @webdriverio/project-committers

2020-11-26 07:13 UTC, christian-bromann requested changes
Thank you for taking this on, a couple of comments:

- let's use TypeScript like in all other command files
- let's add a protocol test in `/e2e/protocol.test.ts
- add some comments to the top of the file (see other devtools commands)

2020-11-26 07:13 UTC, christian-bromann commented on packages/devtools/src/commands/printPage.js
> +        landscaper: options.orientation,
```suggestion
        landscape: options.orientation === 'landscape',
```

2020-11-26 07:13 UTC, christian-bromann commented on packages/devtools/src/commands/printPage.js
> +    const page = DevToolsDriver.getPageHandle()
```suggestion
    const page = this.getPageHandle()
```

2020-11-26 07:13 UTC, christian-bromann commented on packages/devtools/src/commands/printPage.js
> +}
```suggestion
}

```

2020-12-07 08:25 UTC, christian-bromann commented
ping @Maxgit3 any help I can provide on this?

2020-12-10 06:41 UTC, Maxgit3 commented
sorry about the delayed response.  I am looking over creating an e2e test.  I am getting a buffer instead of a string.

2020-12-10 19:47 UTC, Maxgit3 commented
should I save the pdf to a temp location and then confirm if the data is a string?

2020-12-11 08:27 UTC, christian-bromann commented
@Maxgit3 just checking if the return value is a string should be enough.

2020-12-21 01:29 UTC, Maxgit3 commented
updated progress.   looked through the puppeteer documents.  don't see anything about puppeteer returning a string for pdf file.

2020-12-29 00:28 UTC, christian-bromann reviewed
see my comment, happy to assist if anything is unclear

2020-12-29 00:28 UTC, christian-bromann commented on packages/devtools/src/commands/printPage.ts
> +    return page.pdf({
In order for it to return a string an be compliant with the WebDriver protocol I suggest:

```js
const pdfBuffer = await page.pdf({...})
return pdfBuffer.toString()
```

2021-01-11 07:06 UTC, Maxgit3 commented
Sorry about the delay.  I will update

2021-01-14 18:25 UTC, christian-bromann requested changes
one comment, after that it looks good to me

2021-01-14 18:25 UTC, christian-bromann commented on e2e/protocol.test.js
> +        expect(stringData).toBe('string')
```suggestion
        expect(typeof stringData).toBe('string')
```

2021-01-20 20:45 UTC, christian-bromann commented on e2e/protocol.test.js
> +        const stringData = await browser.printPage(opt)
```suggestion
    it('expect string', async () => {
        const stringData = await browser.printPage(
            'horizontal',
            1,
            false,
            '8in',
            '11in',
            '1in',
            '1in',
            '1in',
            '1in',
            false
        )
```

2021-01-21 05:04 UTC, Maxgit3 commented
@christian-bromann sorry, what was the comment?

2021-01-21 07:47 UTC, christian-bromann commented
@Maxgit3 can you update the [protocol parameter types](https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-protocols/protocols/webdriver.json#L207-L262) to accept `string|number`. Also it would be nice if we could type the parameters for the devtools command.

2021-01-25 04:02 UTC, Maxgit3 commented
@christian-bromann did you mean add the parameters in the cli?

2021-01-25 08:11 UTC, christian-bromann commented
> did you mean add the parameters in the cli?

no, in the protocol file that I've linked.

2021-01-28 16:10 UTC, Maxgit3 commented
aww ok thanks

2021-01-29 02:51 UTC, Maxgit3 commented
> @Maxgit3 can you update the [protocol parameter types](https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-protocols/protocols/webdriver.json#L207-L262) to accept `string|number`. Also it would be nice if we could type the parameters for the devtools command.

I am not sure what you mean by type parameters in the devtools command.  should I update the printPage.ts

2021-02-02 08:39 UTC, christian-bromann reviewed
Yes, see my comment below

2021-02-02 08:39 UTC, christian-bromann commented on packages/devtools/src/commands/printPage.ts
> +export default async function printPage(this: DevToolsDriver, options: any) {
The options here are `any` but we should set proper types for it.

2021-02-08 02:52 UTC, Maxgit3 commented
@christian-bromann updated file.  the scale option errors with string type

2021-02-08 13:55 UTC, christian-bromann commented on packages/devtools/src/commands/printPage.ts
> +        pageRanges: pageRanges
```suggestion
        landscape: orientation === 'landscape',
        scale,
        printBackground: background,
        width,
        height,
        margin: { top, right, bottom, left },
        preferCSSPageSize: !shrinkToFit,
        pageRanges
```

2021-02-08 14:24 UTC, christian-bromann commented
@Maxgit3 if you can transform this into a PR and sign the CLA we can get this merged.

2021-02-15 10:55 UTC, christian-bromann commented
ping @Maxgit3

2021-02-16 03:22 UTC, Maxgit3 commented
@christian-bromann sorry about the delay

2021-02-16 08:03 UTC, christian-bromann approved these changes
👍

2021-02-16 08:03 UTC, merged