fix: improve executeAsync typing to allow callback
webdriverio/webdriverio pull request #6207
Opened 2020-12-07 14:08 UTC by DirkoOdendaal

## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

Fixing typing for executeAsync to allow callback in typing.
 #6206

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [ x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [x ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### Reviewers: @webdriverio/project-committers

2020-12-07 14:11 UTC, christian-bromann reviewed
Can we have a test for these typing changes in:

- tests/typings/sync/sync.ts
- tests/typings/webdriverio/async.ts

2020-12-07 14:12 UTC, mgrybyk submitted a review, later dismissed
can you please also fix sync (in wdio-sync package) version and add a test (tests/typings)?

2020-12-07 14:21 UTC, mgrybyk commented
my assumption is you want to make it work like this
```
const result = browser.executeAsync<number>(function (done) {
      done(1)
})
// result is number
```

If so - it doesn't work this way

2020-12-07 20:19 UTC, christian-bromann requested changes

2020-12-07 20:19 UTC, christian-bromann commented on tests/typings/sync/sync.ts
> +const executeAsyncResult = browser.executeAsync(function(a: any, b: any, c: any, d: any, done: any) {
types should be propagated
```suggestion
const executeAsyncResult = browser.executeAsync(function(a, b, c, d, done) {
```

2020-12-07 20:19 UTC, christian-bromann commented on tests/typings/sync/sync.ts
> +executeAsyncResultThree.toEqual('worked');
where does `toEqual` come from?

2020-12-07 20:19 UTC, christian-bromann commented on tests/typings/webdriverio/async.ts
> +    const executeAsyncResult = await browser.executeAsync(function(a: any, b: any, c: any, d: any, done: any) {
same here, types should be implied by the arguments

2020-12-07 20:19 UTC, christian-bromann commented on tests/typings/sync/sync.ts
> +executeAsyncResultThree.toEqual('worked');
we can just call a primitive function to check that the return type is valid, e.g. for numbers `toFixed` or for strings `charCodeAt`

2020-12-07 20:19 UTC, christian-bromann commented
Also please sign the CLA so we can merge the PR once comments are addressed.

2020-12-07 21:37 UTC, christian-bromann approved these changes
LGTM 👍 

Please sign the CLA so we can move forward with this PR. Thank you!

2020-12-07 21:38 UTC, christian-bromann commented
Closed and re-opened PR to see if CLA bot is behind but it seems that you still haven't signed.

2020-12-07 21:39 UTC, christian-bromann commented on packages/webdriverio/webdriverio.d.ts
> -        // there is no way to add callback as last parameter after `...args`.
Can we also remove this comment about the callback in `packages/wdio-sync/webdriverio.d.ts`?

2020-12-08 06:22 UTC, DirkoOdendaal commented
I signed the CLA, so no idea how to progress with this.
https://cla.js.foundation/webdriverio/webdriverio?pullRequest=6207

How else should I sign the CLA?

2020-12-08 08:10 UTC, christian-bromann commented
> How else should I sign the CLA?

@DirkoOdendaal make sure that you sign it with the same email you have used to make the commits.

2020-12-08 09:47 UTC, DirkoOdendaal commented
> @DirkoOdendaal make sure that you sign it with the same email you have used to make the commits.

@christian-bromann That is what I did. It asks you to login with your github account, so no idea why it would not match.
I've tried again on an incognito window too.

Could you please trigger the check again?

2020-12-08 09:55 UTC, christian-bromann commented
@DirkoOdendaal you need to sign the CLA with this email: `entelect@rmal1508122.oc.rabonet.com`

2020-12-08 10:48 UTC, DirkoOdendaal commented
> @DirkoOdendaal you need to sign the CLA with this email: `entelect@rmal1508122.oc.rabonet.com`

I might need to recreate the PR. Looks like the username and email was not properly set on my end.
Just triggered the build/tests again to see if my config is setup correctly now.

2020-12-08 10:59 UTC, closed without merging