Issue #6511 fix
webdriverio/webdriverio pull request #6512
Opened 2021-02-25 17:15 UTC by patkunicki

## Proposed changes

Replace `specArguments.pop()` with `specArguments[1]` incase specArguments has more than two indexes.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### Reviewers: @webdriverio/project-committers

2021-03-01 09:04 UTC, christian-bromann requested changes

2021-03-01 09:04 UTC, christian-bromann commented on packages/wdio-utils/tests/test-framework/testInterfaceWrapper.test.js
> +        fn('test title', specFn, {})
Can we make this test a bit more meaningful and assert what has been passed in?
```suggestion
        fn('test title', specFn, { options: { foo: 'bar' } })
```

2021-03-01 09:04 UTC, christian-bromann commented on packages/wdio-utils/tests/test-framework/testInterfaceWrapper.test.js
>              { specFn, specFnArgs: ['foo', 'bar'] },
It should be propagated here, right?

2021-03-30 11:08 UTC, christian-bromann commented
@patkunicki any updates? Anything I can help with?

2021-03-30 15:01 UTC, patkunicki commented
Made the update, hopefully its good now

2021-03-30 15:07 UTC, christian-bromann approved these changes
👍  thanks

2021-03-30 15:17 UTC, merged