fix sync browser types
webdriverio/webdriverio pull request #6625
Opened 2021-03-27 16:35 UTC by giacomomagini

## Proposed changes

Types for the sync `browser` object are set to `unknown`.
Copy types for the sync `browser` interface.

https://github.com/webdriverio/webdriverio/issues/6622

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [ ] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### Reviewers: @webdriverio/project-committers

2021-03-27 17:09 UTC, christian-bromann requested changes
I think most of them we don't need as we copy them over via:

```ts
{
    [K in keyof Omit<BrowserCommandsType, 'execute'>]: (...args: Parameters<BrowserCommandsType[K]>) => ThenArg<ReturnType<BrowserCommandsType[K]>>
}
```

So only commands that work with generics as we can't propagate that. Let's avoid duplicate definition as much as possible and only keep `call` here.

2021-03-28 11:21 UTC, giacomomagini commented
Makes sense, I got threw off by some `any` in the signature while trying the type but they seem coming from the original function. Same for some missing return type.

2021-03-29 07:36 UTC, christian-bromann reviewed
Can we add `call` to the exclude list before?
```suggestion
export type BrowserCommandsTypeSync = {
-    [K in keyof Omit<BrowserCommandsType, 'execute'>]: (...args: Parameters<BrowserCommandsType[K]>) => ThenArg<ReturnType<BrowserCommandsType[K]>>
+    [K in keyof Omit<BrowserCommandsType, 'execute' | 'call'>]: (...args: Parameters<BrowserCommandsType[K]>) => ThenArg<ReturnType<BrowserCommandsType[K]>>
} & {
```

Our define the list of commands that we overwrite in an extra type and use keyof, e.g.

```suggestion
export type BrowserCommandsTypeSync = {
-    [K in keyof Omit<BrowserCommandsType, 'execute'>]: (...args: Parameters<BrowserCommandsType[K]>) => ThenArg<ReturnType<BrowserCommandsType[K]>>
+    [K in keyof Omit<BrowserCommandsType, keyOf CommandsWithGenerics>]: (...args: Parameters<BrowserCommandsType[K]>) => ThenArg<ReturnType<BrowserCommandsType[K]>>
} & {
```

2021-03-29 09:57 UTC, christian-bromann commented on packages/webdriverio/src/types.ts
> +    ) => ReturnValue,
```suggestion
    ) => ReturnValue
```

2021-03-29 09:58 UTC, christian-bromann approved these changes
👍

2021-03-29 09:59 UTC, christian-bromann commented
It seems that one to of our typing tests fails: https://github.com/webdriverio/webdriverio/blob/main/tests/typings/sync/sync.ts#L70-L73

2021-03-30 15:49 UTC, giacomomagini commented
@christian-bromann I checked the failing test but I don't know where that global `browser` var comes from.
If I try to use the type in the file where i made the changes I can see the same line (`<number>browser.call(...)`) working fine.
Any heads up?

2021-03-30 15:59 UTC, christian-bromann commented
> but I don't know where that global `browser` var comes from.

It is just a test file that expects the browser to be registered in global scope. This is the case if wdio types are registered in [tsconfig.json](https://github.com/webdriverio/webdriverio/blob/main/tests/typings/sync/tsconfig.json#L6-L22).

I believe the following two files need to be updated:
- tests/typings/webdriverio/async.ts
- tests/typings/sync/sync.ts

Both currently have similar examples for the call command:
```ts
const callResult = <number>browser.call(() =>
    new Promise(resolve => setTimeout(() => resolve(4), 1))
)
callResult.toFixed(2)
```
I think with this PR we should be able to remove the conversion and only have:
```ts
const callResult = browser.call(() =>
    new Promise(resolve => setTimeout(() => resolve(4), 1))
)
callResult.toFixed(2)
```

right?

2021-03-31 16:59 UTC, giacomomagini commented
`I think with this PR we should be able to remove the conversion and only have` -> yes, but it should work also specifying the generic.

The type was wrong, the correct function return type is `Promise<T>` instead of `T`.

It's fixed now! :)

2021-03-31 17:13 UTC, christian-bromann approved these changes
👍  thank you so much!

2021-03-31 17:14 UTC, christian-bromann commented
@giacomomagini would you mind signing the CLA?

2021-03-31 17:16 UTC, giacomomagini commented
I've signed it 🤔 I can't see the button anymore when i open the link.

2021-03-31 18:12 UTC, giacomomagini commented
Sorry, my global git config had my work email. I re-pushed with my private email in the commit.
Thanks for helping 😄

2021-03-31 19:29 UTC, christian-bromann commented
Perfect, thanks!

2021-03-31 19:29 UTC, merged