The ability to use devtools-service in the launches on the selenoid
webdriverio/webdriverio pull request #6669
Opened 2021-04-07 15:04 UTC by fedoseevGIT

## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

This Pull Request fixes WebSocket connection issue when running on Selenoid. To test this fix, you need to specify `selenoidWSEndpoint: true` in wdio.conf.js

I described a similar problem in https://github.com/webdriverio/webdriverio/issues/6665, where I wanted to use the attach function to get the devtools session, but I managed to completely avoid this by fixing the error at the start of WDIO

### Reviewers: @webdriverio/project-committers

2021-04-07 15:21 UTC, BorisOsipov requested changes
Please have look into comments

2021-04-07 15:22 UTC, BorisOsipov commented
@fedoseevGIT also please add unit test like this https://github.com/webdriverio/webdriverio/blob/9d2220e89144b0ca69232737957ad5fc32ca1300/packages/webdriverio/tests/commands/browser/getPuppeteer.test.ts#L124

2021-04-07 15:33 UTC, christian-bromann reviewed
This should not be handled through a top level option but rather via custom Selenoid capabilities. Also this doesn't address the problem of being able to attach to a running Selenoid session which was discussed in the issue, right?

2021-04-07 15:33 UTC, christian-bromann commented on packages/webdriverio/src/commands/browser/getPuppeteer.ts
> +            browserWSEndpoint: `ws://${this.config.hostname}:4444/devtools/${this.sessionId}`,
Why can't Selenoid return their WebSocket url like Selenium does?

2021-04-07 15:39 UTC, BorisOsipov commented on packages/webdriverio/src/commands/browser/getPuppeteer.ts
> +            browserWSEndpoint: `ws://${this.config.hostname}:4444/devtools/${this.sessionId}`,
@christian-bromann https://github.com/aerokube/selenoid/issues/1063#issuecomment-782071381

2021-04-07 15:48 UTC, BorisOsipov commented
>Also this doesn't address the problem of being able to attach to a running Selenoid session which was discussed in the issue, right?

It is not so "important" feature. This PR enables all wdio CDP features for Selenoid. That is great moving forward for users who want CDP and remote browsers.

2021-04-07 15:53 UTC, BorisOsipov commented
>This should not be handled through a top level option but rather via custom Selenoid capabilities. 

Agree. I made similar changes few months ago, but didn't find a way how I can get know that current session run on Selenoid or not and I abandoned this changes.

2021-04-07 15:55 UTC, christian-bromann commented
We can just say, if we find `'selenoid:options'` within the capabilities we say it is Selenoid.

2021-04-07 16:05 UTC, BorisOsipov commented
@christian-bromann inside `getPuppeteer.ts` `this.capabilites` look like this for selenoid session
```
[0-0] {
  acceptInsecureCerts: true,
  browserName: 'chrome',
  browserVersion: '89.0.4389.114',
  chrome: {
    chromedriverVersion: '89.0.4389.23 (61b08ee2c50024bab004e48d2b1b083cdbdac579-refs/branch-heads/4389@{#294})',
    userDataDir: 'C:\\Users\\bo\\AppData\\Local\\Temp\\scoped_dir25348_492577889'
  },
  'goog:chromeOptions': { debuggerAddress: 'localhost:53124' },
  networkConnectionEnabled: false,
  pageLoadStrategy: 'normal',
  platformName: 'windows',
  proxy: {},
  setWindowRect: true,
  strictFileInteractability: false,
  timeouts: { implicit: 0, pageLoad: 300000, script: 30000 },
  unhandledPromptBehavior: 'dismiss and notify',
  'webauthn:extension:largeBlob': true,
  'webauthn:virtualAuthenticators': true
}
```

it for capabilities in config 
```
  capabilities: [{
    maxInstances: 1,
    browserName: 'chrome',
    acceptInsecureCerts: true,
    'selenoid:options': {
      enableVNC: true,
      enableVideo: true
    }
  }],
```

So I can't decide from `this.capabilites` is it Selenoid session or not.

2021-04-07 16:20 UTC, christian-bromann commented
@BorisOsipov there is also `this.requestedCapabilities` which should return you the right ones.

2021-04-07 20:34 UTC, BorisOsipov commented
@fedoseevGIT Thank you for the PR. Close this in favor of https://github.com/webdriverio/webdriverio/pull/6673

2021-04-07 20:34 UTC, closed without merging

2021-04-08 06:43 UTC, fedoseevGIT commented
Thank you very much:)

2021-04-08 06:52 UTC, fedoseevGIT commented
Left only a small comment about path - it is superfluous on the way to WS connection: https://github.com/webdriverio/webdriverio/pull/6673/files#r609364460