added run test command suggestion for ts file
webdriverio/webdriverio pull request #6979
Opened 2021-06-06 14:07 UTC by sadabnepal

## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)
Fix of #6978 
## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### Reviewers: @webdriverio/project-committers

2021-06-07 07:27 UTC, christian-bromann requested changes
Rather than defining two almost identical messages I suggest to use `util.format`, e.g.:

```js
export const CONFIG_JS_HELPER_SUCCESS_MESSAGE = `
Configuration file was created successfully!
To run your tests, execute:
$ npx wdio run wdio.conf.%s
```

and then:

```js
console.log(util.format(CONFIG_TS_HELPER_SUCCESS_MESSAGE, answers.isUsingCompiler === COMPILER_OPTIONS.ts ? 'ts' : 'js'))
```

2021-06-07 07:27 UTC, christian-bromann commented
Also please make sure the unit tests are passing. Thanks!

2021-06-07 15:20 UTC, sadabnepal commented
> Also please make sure the unit tests are passing. Thanks!

@christian-bromann  I am new here and might need a bit of guidance on how to write unit test for this scenario.

2021-06-07 21:51 UTC, christian-bromann requested changes
The code looks good, now updating the unit test is important.

2021-06-07 21:51 UTC, christian-bromann commented on packages/wdio-cli/src/commands/config.ts
> +import * as inquirer from 'inquirer'
Can we revert this? The way TypeScript is setup does not require such imports.

2021-06-07 21:51 UTC, christian-bromann commented on packages/wdio-cli/src/commands/config.ts
> +import * as yargs from 'yargs'
same

2021-06-07 21:51 UTC, christian-bromann commented on packages/wdio-cli/src/commands/config.ts
> +    CONFIG_HELPER_SUCCESS_MESSAGE,
```suggestion
    CONFIG_HELPER_SUCCESS_MESSAGE
```

2021-06-08 02:00 UTC, sadabnepal commented on packages/wdio-cli/src/commands/config.ts
> +import * as yargs from 'yargs'
Reverted

2021-06-08 02:01 UTC, sadabnepal commented on packages/wdio-cli/src/commands/config.ts
> +    CONFIG_HELPER_SUCCESS_MESSAGE,
removed comma

2021-06-30 14:05 UTC, sadabnepal commented
Closing this PR, I will create new one as this is failing on sample run

2021-06-30 14:05 UTC, closed without merging

2021-07-12 09:59 UTC, christian-bromann commented
@sadabnepal can you point me to the new PR?