Use the Ky request library in a web browser context instead of Got
webdriverio/webdriverio pull request #6999
Opened 2021-06-10 03:36 UTC by jlipps

## Proposed changes

Some time ago, WebdriverIO standardized on Got as the request library. Unfortunately this broke downstream projects like Web2Driver which need to be able to bundle the webdriver package for the web. This PR adds in support for the Ky browser-based request library, and selects it in a non-Node.js environment.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [X] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [X] I have added proper type definitions for new commands (if appropriate)

## Further comments

There are currently no tests for the browser-based client, since I think that would be a pretty big update to the whole test environment. I'm open to hearing how to approach testing (beyond using it in my own project).

### Reviewers: @webdriverio/project-committers

2021-06-10 06:55 UTC, christian-bromann requested changes
Thanks for pushing this forward 🙏 

Overall looks good to me, some suggestions:

- can we also have a unit test for `request-browser.ts`?
- can we change the folder structure to the following:

```
/ src
    |- command.ts
    |- /request
        |- index.ts (current request.ts)
        |- node.ts (current request-node.ts)
        |- factory.ts (current request-factory.ts)
        |- browser.ts (current request-browser.ts)
   |- ...
```

2021-06-10 06:55 UTC, christian-bromann commented on packages/webdriver/tests/request.test.ts
> +            console.log(req.defaultOptions)
```suggestion
```

2021-06-11 16:38 UTC, jlipps commented
Sounds good, I'm working on these changes. I have to mock Ky completely since we don't even want to import it from Node (it's exported in a way that's designed to be bundled)

2021-07-15 23:40 UTC, jlipps commented
ok @christian-bromann I added tests to mirror the tests for the node version of the requests, and I've also tested in Web2Driver (that e2e suite passed). There seem to be some CI issues here with conflicting versions of types that I'm not sure how to resolve though.

2021-07-16 06:59 UTC, christian-bromann commented
The code looks good. Is the filename `brower.ts` intentional or a typo? I can take a look at the typing issue.

2021-07-16 17:15 UTC, christian-bromann commented
@jlipps can you revert your changes in `package-lock.json`? It should resolve the typing problems.

2021-07-16 17:20 UTC, jlipps commented
> The code looks good. Is the filename brower.ts intentional or a typo? I can take a look at the typing issue.

Hmm it was an extra file somehow, obviously a typo. I removed it.

> can you revert your changes in package-lock.json? It should resolve the typing problems.

OK, let's see how that works!

2021-07-16 17:30 UTC, jlipps commented
@christian-bromann even without any package-lock changes there seem to be some typing conflicts on windows and some versions of node on linux. but on other platforms it looks OK. that's odd, right?

2021-07-19 09:25 UTC, christian-bromann commented
Rerunning, just saw it also happening in an other PR.

2021-07-19 16:24 UTC, jlipps commented
rerunning doesn't seem to have helped. 🤔

2021-07-19 16:32 UTC, christian-bromann commented
@jlipps is this something you can reproduce locally, via:

```sh
$ rm -r node_modules package-lock.json
$ npm install
$ npm run setup-full
# if this fails you can only compile via
$ npm run build
```

?

2021-07-19 18:50 UTC, jlipps commented
@christian-bromann all of those commands completed successfully (though of course they resulted in a package-lock.json which differs from the one on `main`). would you like me to run any other commands, or push the lockfile changes?

2021-07-21 16:53 UTC, jlipps commented
Any more thoughts on this @christian-bromann? If you pull the branch and run tests, does it work? Want me to push lockfile updates? Or run a lockfile update on `main` so that I can rebase on it?

2021-07-22 11:14 UTC, christian-bromann commented
closing in favor of https://github.com/webdriverio/webdriverio/pull/6999

2021-07-22 11:14 UTC, closed without merging