Set the job name before a suite is run
webdriverio/webdriverio pull request #7672
Opened 2021-11-09 19:21 UTC by gabriel-kohen-by

## Proposed changes

Per https://github.com/webdriverio/webdriverio/issues/7609 we need to account for suite `before` logic will be long running or failing and we want to give intication early on running the suite's tests of what is running.

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

- [X] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

### Reviewers: @webdriverio/project-committers

2021-11-09 19:50 UTC, christian-bromann requested changes
Thanks for taking a stab at this!

Let's add one or multiple test cases [here](https://github.com/gabriel-kohen-by/webdriverio/blob/main/packages/wdio-sauce-service/tests/service.test.ts#L60-L66) and ensure that the if statement is only executed if situation is as expected.

2021-11-13 18:02 UTC, gabriel-kohen-by commented
@christian-bromann, thanks for the feedback. I've tweaked and added some assertions to account for the new logic. Let me know if there is anything I need to change.

2021-11-15 12:20 UTC, christian-bromann approved these changes
LGTM 👍  thanks a lot!

2021-11-15 12:20 UTC, christian-bromann commented on packages/wdio-sauce-service/tests/service.test.ts
> +            { outputDir: '/foo/bar' } as any
```suggestion
        { outputDir: '/foo/bar' } as any
```

2021-11-15 12:46 UTC, gabriel-kohen-by commented
@christian-bromann , not sure why the e2e failed on the Mac. Can't think the changes are related to this failure. Is the e2e flaky in nature?

2021-11-15 13:40 UTC, christian-bromann commented
@gabriel-kohen-by yeah, the windows e2e tests aren't that stable atm. Will go ahead and merge. Thanks a lot!

2021-11-15 13:41 UTC, merged

2021-11-15 14:46 UTC, gabriel-kohen-by commented
Thanks for merging @christian-bromann. How does the release process works as far as making it to GA?

2021-11-15 14:55 UTC, christian-bromann commented
I just need to kick off a GitHub action to release a new version. Will do so now.

2021-11-21 07:09 UTC, wswebcreation commented
This breaks setting the job name in Jasmine, because the `suiteTitle` is `Jasmine__TopLevel__Suite` and the `fullName` is `null`, so no alternative. Will fix this in another PR