Fix for Jasmine webdriverio exception not failing suite
webdriverio/webdriverio pull request #7823
Opened 2021-12-18 09:24 UTC by praveendvd

## Proposed changes

This fixes [🐛 Bug]: Spec status shows passed even if one spec failed #7822 . The emit(e,) was throwing erro because internally  we were using difference check between actual and expectd , the actual in this case was proxy instead of string

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [X] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### Reviewers: @webdriverio/project-committers

2021-12-20 08:14 UTC, christian-bromann requested changes
Can we add a unit test for this (e.g. [here](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-reporter/tests/stats/test.test.ts)) to ensure we don't add any regression moving forward?

2021-12-20 12:22 UTC, praveendvd commented
@christian-bromann  i am not able to mock the this.complete function could you help me here:


        stat.complete = jest.fn(() => {})
        stat.fail([new AssertionError({ message: 'foobar\nExpected: foo\nReceived: bar42', actual: 'true', expected: 'false' })])

![image](https://user-images.githubusercontent.com/45095911/146766622-e50f263f-e462-4f9f-9546-9803197f3a73.png)

2021-12-20 13:47 UTC, praveendvd commented
@christian-bromann  Thank you so much , i did the same but it was not helping in validating if error is thrown , now i used spyon to validate that the stringify method is not thrown for promise

2021-12-23 11:30 UTC, christian-bromann approved these changes
LGTM 👍  thanks!

2021-12-23 11:30 UTC, merged