Fix: Throw error if path to tsconfig.json is incorrect
webdriverio/webdriverio pull request #8217
Opened 2022-04-13 19:04 UTC by harsha509

## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [ ] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### Reviewers: @webdriverio/project-committers

2022-04-13 20:25 UTC, christian-bromann requested changes
I think this deserves a unit test.

2022-04-13 20:25 UTC, christian-bromann commented on packages/wdio-runner/src/index.ts
> +            if (!fs.existsSync(args.autoCompileOpts.tsNodeOpts.project))
```suggestion
            if (!fs.existsSync(args.autoCompileOpts?.tsNodeOpts?.project))
```
```suggestion
            if (!fs.existsSync(args.autoCompileOpts.tsNodeOpts.project))
```

2022-04-13 20:25 UTC, christian-bromann commented on packages/wdio-runner/src/index.ts
> +                log.error('Path to "tsconfig.json" is incorrect. Is it correclty set in config -> tsNodeOpts ? ')
Let's throw an error here because if someone really defines this property it should point to a correct file

2022-04-13 20:25 UTC, christian-bromann commented on packages/wdio-runner/src/index.ts
> +                log.error('Path to "tsconfig.json" is incorrect. Is it correclty set in config -> tsNodeOpts ? ')
Let's throw an error here because if someone really defines this property it should point to a correct file

2022-04-21 07:39 UTC, harsha509 commented
Having some wierd type issue. Will raise PR again with Test included!

2022-04-21 07:39 UTC, closed without merging