[Browserstack-service] Local App file upload to browserstack for Appium sessions
webdriverio/webdriverio pull request #8864
Opened 2022-09-16 12:00 UTC by avinash-bharti

## Proposed changes

This PR:

- Add support for app upload using the local app file path to browserstack
  - app upload used in appium sessions
  - the value of the app can be a file path, app_url, custom_id, shareable_id. [ref](https://www.browserstack.com/docs/app-automate/appium/set-up-tests/specify-app)
  - custom_id can also be provided while uploading the app

`v7` PR: https://github.com/webdriverio/webdriverio/pull/8856

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### Reviewers: @webdriverio/project-committers

2022-09-20 10:58 UTC, christian-bromann requested changes
Some comments. Please also adapt changes to the other branch. Thanks!

2022-09-20 10:58 UTC, christian-bromann commented on packages/wdio-browserstack-service/README.md
> +[specify-application-under-test](https://www.browserstack.com/docs/app-automate/appium/set-up-tests/specify-app)
```suggestion
### app
[Appium](https://appium.io/) set this with app file path available locally on your machine to use the app as [application under test](https://www.browserstack.com/docs/app-automate/appium/set-up-tests/specify-app) for Appium sessions.
```

2022-09-20 10:58 UTC, christian-bromann commented on packages/wdio-browserstack-service/src/launcher.ts
> +                return process.emit('SIGTERM')
We should throw a `SevereServiceError` here which causes the service to stop the test run. You can import it via:

```js
import { SevereServiceError } from 'webdriverio'
```

Add `webdriverio` as peer dependency to make this import possible.

2022-09-20 10:58 UTC, christian-bromann commented on packages/wdio-browserstack-service/src/launcher.ts
> +            if (['.apk', '.aab', '.ipa'].includes(path.extname(app.app!))){
Let's move this (`['.apk', '.aab', '.ipa']`) to `constant.ts` for better readability.

2022-09-20 10:58 UTC, christian-bromann commented on packages/wdio-browserstack-service/src/launcher.ts
> +                    return process.emit('SIGTERM')
Same as above.

2022-09-20 10:58 UTC, christian-bromann commented on packages/wdio-browserstack-service/src/launcher.ts
> +        return new Promise((resolve, reject) => {
Can we use async await instead?

2022-09-20 10:58 UTC, christian-bromann commented on packages/wdio-browserstack-service/src/launcher.ts
> +                return reject('[Invalid format] app should be string or an object')
And throw an `SevereServiceError` error here?

2022-09-20 10:58 UTC, christian-bromann commented on packages/wdio-browserstack-service/src/launcher.ts
> +                return reject(`[Invalid app property] supported properties are {id<string>, path<string>, custom_id<string>, shareable_id<string>}.
and here.

2022-09-20 10:58 UTC, christian-bromann commented on packages/wdio-browserstack-service/src/launcher.ts
> +            throw TypeError('Capabilities should be an object or Array!')
```suggestion
            throw new SevereServiceError('Capabilities should be an object or Array!')
```

2022-09-21 12:22 UTC, avinash-bharti commented
@christian-bromann Required changes has been done on both PR, thanks

2022-09-21 15:52 UTC, christian-bromann commented on packages/wdio-browserstack-service/src/launcher.ts
> +            throw new Error(`[Invalid app property] supported properties are {id<string>, path<string>, custom_id<string>, shareable_id<string>}.
```suggestion
            throw new SevereServiceError(`[Invalid app property] supported properties are {id<string>, path<string>, custom_id<string>, shareable_id<string>}.
```

2022-09-21 15:52 UTC, christian-bromann commented on packages/wdio-browserstack-service/src/launcher.ts
> +
```suggestion
```

2022-09-21 17:06 UTC, avinash-bharti commented
@christian-bromann Thanks for reviewing.
 Have pushed the required changes in both PR, Please have a look.

2022-09-23 05:10 UTC, christian-bromann commented on packages/wdio-browserstack-service/README.md
> +[Appium](https://appium.io/) set this with app file path available locally on your machine to use the app as [application under test](https://www.browserstack.com/docs/app-automate/appium/set-up-test
```suggestion

[Appium](https://appium.io/) set this with app file path available locally on your machine to use the app as [application under test](https://www.browserstack.com/docs/app-automate/appium/set-up-tests/specify-app) for Appium sessions.
```

2022-09-23 05:12 UTC, christian-bromann approved these changes
LGTM 👍  Thank you!

@Ankit098 any comments or good to merge?

2022-09-23 05:29 UTC, Ankit098 commented
Hey @christian-bromann! LGTM..

2022-09-23 14:50 UTC, merged